[package]
name = "muonline-service"
version = "0.1.0"
authors = ["Elliott Linder <elliott@linder.bz>"]

[dependencies]
bcrypt = "0.2"
murust-data-model = { path = "../murust-data-model" }
murust-repository = { path = "../murust-repository" }

[dev-dependencies]
lazy_static = "1.0"